# Generated by Django 3.2.3 on 2021-05-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(db_column='UID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='USERNAME', max_length=20, unique=True)),
                ('password', models.CharField(db_column='PASSWORD', max_length=30)),
                ('register_time', models.DateField(db_column='REGISTER_TIME')),
                ('role', models.IntegerField(db_column='ROLE')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
