# Generated by Django 3.2.3 on 2021-05-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_unit', models.IntegerField(db_column='单价')),
                ('price_sum', models.IntegerField()),
                ('area_size', models.IntegerField()),
            ],
        ),
    ]
