# Generated by Django 3.2.3 on 2021-05-31 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
    ]
