# Generated by Django 3.2.3 on 2021-05-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField(blank=True, null=True)),
                ('toward', models.TextField(blank=True, null=True)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('building_area', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('decoration', models.TextField(blank=True, null=True)),
                ('floor', models.TextField(blank=True, null=True)),
                ('unit_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'house',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseOfCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField(blank=True, null=True)),
                ('case_type', models.TextField(blank=True, null=True)),
                ('case_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'house_of_case',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intermediary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField(blank=True, null=True)),
                ('intermediary_name', models.TextField(blank=True, null=True)),
                ('phone', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intermediary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationOfHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('community_name', models.TextField(blank=True, null=True)),
                ('part_area', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location_of_house',
                'managed': False,
            },
        ),
    ]
