# Generated by Django 3.2.3 on 2021-05-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_house_houseofcase_intermediary_locationofhouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
