# Generated by Django 3.2.3 on 2021-05-31 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='houseofcase',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='intermediary',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='locationofhouse',
            options={'managed': True},
        ),
    ]
