# Generated by Django 3.2.3 on 2021-05-31 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210531_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField(blank=True, null=True)),
                ('case_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'case',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HouseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'house_case',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='HouseOfCase',
        ),
        migrations.RemoveField(
            model_name='house',
            name='id',
        ),
        migrations.AddField(
            model_name='house',
            name='admin_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='housecase',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.house'),
        ),
    ]
