# Generated by Django 3.2.3 on 2021-06-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210531_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='house_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
